version: "3"

services:
  db:
    build: ./database
    container_name: pinnacle_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spotlight_db
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes: 
      - ./database/data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: ./server
    container_name: pinnacle_server
    restart: always
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on: 
      - db